project:
  type: website

website:
  title: "Curso de Estad√≠stica"
  favicon: bar-chart-business-analytics-statistics-svgrepo-com.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/equihuam/M3-2023_DiseExp_anova
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

